### ISSUE TITLE
No validation error is displayed

### ISSUE THREAD

**Issue by KouloukLeGrand** [danvick/form_builder_file_picker#22]
Hi,

When calling `_formKey.currentState!.fields["filePicker"]!.invalidate("Validation error");` (assuming `_formKey` is a `GlobalKey<FormBuilderState>` and the _filePicker_ field is a `FormBuilderFilePicker`) or otherwise using the `validator:` property of `FormBuilderFilePicker`, no error message appears on the field.

Do I have to tinker my own solution or am I missing something?

**Comment by K-Zawis** [comment]
Same here.

```
FormBuilderFilePicker(
    name: 'pdf_file',
    maxFiles: 1,
    type: FileType.custom,
    allowedExtensions: const ['pdf'],
    decoration: const InputDecoration(
        labelText: 'PDF File *',
    ),
    validator: FormBuilderValidators.required(context),
),
```

Validation fails but border doesn't change nor does the error message show.

I managed to get it working by using the:

 ```
decoration: InputDecoration(
    labelText: 'PDF File *',
    errorText: errorText,
),
```

method.

This may solve the issue for you. However it's not ideal when working with dynamic forms like I am at all...

------------

Any plans fixing this? :confused:
