### ISSUE TITLE
[Request] Add camera support

### ISSUE THREAD

**Issue by jasonlaw** [danvick/form_builder_file_picker#6]
Can you please add the camera support?
Btw, the version of flutter_form_builder seems not up to date.

Many thanks in advance.

**Comment by breezage** [comment]
This is a compatible addon to [FormBuilder ](https://pub.dev/packages/flutter_form_builder) plugin please check documentation of FormBuilder. `FormBuilderImagePicker `is available in the main plugin and you can use it access device gallery or camera.

**Comment by jasonlaw** [comment]
Indeed I have overlooked that, thanks for pointing out.
